plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Role
    prefix: role
  - key: tags.Name
    prefix: name
hostnames:
  - private-ip-address
compose:
  ansible_host: public_ip_address
