fullnameOverride: argocd
configs:
  params:
    server.insecure: true
    server.basehref: "/"
  cm:
    admin.enabled: true
  secret:
    createSecret: false
server:
  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
